### ISSUE TITLE
Not working with 1.47

### ISSUE THREAD

**Issue by bisoft2** [TheLazyTomcat/SII_Decrypt#1]
It's not working with the new version

**Comment by TheLazyTomcat** [comment]
I will look into it, but no promises.

**Comment by jorensanbar** [comment]
Hello! Check this Fork, is working: https://github.com/AlexKERNEL/SII_Decrypt_1.5.x 

Maybe you can migrate the code

**Comment by TheLazyTomcat** [comment]
I know about this, but some things are missing there and the changes are not that big to warrant a merge.

**Comment by TheLazyTomcat** [comment]
Well, it seems there is no demand for this tool any more (there are forks and a rewrite to C#), so...
I will do new version (1.5.3), and if nothing changes, it will most probably be the last version from me. I am completely offline most of the year, so I cannot react to changes and do timely updates, therefore the project moved on without me, which is understandable.

**Comment by dowmeister** [comment]
There are ports in c#?
I havent found yet one, all github repositories are closed or private now

Anyway, thanks for your work and high availablity

**Comment by TheLazyTomcat** [comment]
The one I know is on gitlab: https://gitlab.com/jammerxd/sii-decryptsharp
Dunno whether there are others.

**Comment by TheLazyTomcat** [comment]
Note...
I was also working on more advanced new version (SII Decrypt 2). Currently it is just a bunch of units where I was testing ideas (full streaming processing (very limited memory footprint), back-saving (encoding and encrypting the saves back), binary type binding (for hotfixes and quick updates), partial decoding (for external tools that do not need textual form), ...). Right now it is on hold, but does anyone reading this think I should finish that? I mean, it is a LOT of work, and if nobody would use it....

**Comment by AlexKERNEL** [comment]
> Note... I was also working on more advanced new version (SII Decrypt 2). Currently it is just a bunch of units where I was testing ideas (full streaming processing (very limited memory footprint), back-saving (encoding and encrypting the saves back), binary type binding (for hotfixes and quick updates), partial decoding (for external tools that do not need textual form), ...). Right now it is on hold, but does anyone reading this think I should finish that? I mean, it is a LOT of work, and if nobody would use it....

I would be happy to work with this ❤️

**Comment by TheLazyTomcat** [comment]
1.5.3 **should** work in latest ETS2/ATS, so closing.
