### ISSUE TITLE
SII Decryt cant decrypt some files

### ISSUE THREAD

**Issue by Snitrxm** [TheLazyTomcat/SII_Decrypt#2]
In my case.  I use SII_Decrypt for a tool. I found out that some files SII_Decrypt cant decrypt. These files when I try to decrepy starts with "BSII"

BSII             economy9      bank9      player:   	   companies:      garages      garage_ignore_list9   
   game_progress9      event_queue9   	   mail_ctrl9      oversize_offer_ctrl'   	   game_time      game_time_secs'      game_time_initial'      achievements_added5      new_game'      total_distance'      experience_points'      adr'   	   long_dist'      heavy'      fragile'      urgent'   
   mechanical(      user_colors9      delivery_log9   	   ferry_log9      police_offence_log'      stored_camera_mode'      stored_actor_state'      stored_high_beam_style      stored_actor_windows_state'      stored_actor_wiper_mode'      stored_actor_retarder'       stored_display_mode_on_dashboard'      stored_display_mode_on_gps'      stored_dashboard_map_mode'      stored_world_map_zoom3      stored_online_job_id      stored_online_gps_behind      stored_online_gps_ahead:   "   stored_online_gps_behind_waypoints:   !   stored_online_gps_ahead_waypoints:   !   stored_online_gps_avoid_waypoints9      stored_special_job9      police_ctrl'      stored_map_state1      stored_gas_pump_money      stored_weather_change_timer'      stored_current_weather      stored_rain_wetness%   	   time_zone      time_zone_name      last_ferry_position5      stored_show_weigh5      stored_need_to_weigh      stored_nav_start_pos      stored_nav_end_pos      stored_gps_behind      stored_gps_ahead:      stored_gps_behind_waypoints:      stored_gps_ahead_waypoints:      stored_gps_avoid_waypoints      stored_start_tollgate_pos'      stored_tutorial_state:      stored_map_actions'      clean_distance_counter'      clean_distance_max'       no_cargo_damage_distance_counter'      no_cargo_damage_distance_max'      no_violation_distance_counter'      no_violation_distance_max'      total_real_time      real_time_seconds      visited_cities(      visited_cities_count      last_visited_city4      discovered_cutscene_items,       discovered_cutscene_items_states      unlocked_dealers      unlocked_recruitments'      total_screeshot_count'    

This a example how the file looks like after decrypting

**Comment by Wiechu14** [comment]
I have the same issue

**Comment by TheLazyTomcat** [comment]
Can any of you provide the problematic file? Judging from the example, it seem the file was decrypted but not decoded. Are you using latest version of the tool?

**Comment by github-venkat** [comment]
Here are the files 

[done.txt](https://github.com/TheLazyTomcat/SII_Decrypt/files/12582201/done.txt)

<Change game.txt to game.sii>
[game.txt](https://github.com/TheLazyTomcat/SII_Decrypt/files/12582203/game.txt)

**Comment by TheLazyTomcat** [comment]
Latest version (1.5.3) decodes that file without any problem.

You can find latest compiled executables in a "bin" branch (https://github.com/TheLazyTomcat/SII_Decrypt/tree/bin, eg. https://github.com/TheLazyTomcat/SII_Decrypt/raw/bin/Program_GUI/Delphi/Release/win_x86/SII_Decrypt.exe), or download them here https://www.dropbox.com/sh/lhz3m1n56ed7nwb/AACqtc79HzlJIj7oX95w7c3ea?dl=0
